'use strict';
//This function will get the localStorage items and convert it to a string array
function get_todos(){
    var todos = new Array;
    //If the function is called for the first time
    //the localStorage would be empty and the todos_str will be null
    var todos_str = localStorage.getItem('todo');
    //If localStorage is not empty
    if(todos_str !== null){ 
        //converting the JSON string back to JavaScript data
        //so we could display it in the browser 
        todos = JSON.parse(todos_str);
    }

    return todos;
}

//This function will be called when the user clicks on the button
//It will add a task to the previously defined tasks 
function add(){
    //getting the value of the input with id task
    var task = document.getElementById('task').value;
    //getting the string array from localStorage
    var todos = get_todos();
    //add the new task to the array
    todos.push(task);
    //save the new todos array in the localStorage
    //stringify method Converts a JavaScript value to a JavaScript Object Notation (JSON) string.
    localStorage.setItem('todo', JSON.stringify(todos));

    show();

    //avoid any further actions generated by the click event
    return false;
}

//This function will clear the value from the input when the value is set in 
//the localStorage
function clearDefault(a){
    if(a.defaultValue == a.value){
        a.value = "";
    }
}

//This function will be called when the user clicks on the delete button
//It will remove a task from the previously defined tasks 
function remove(){
    //this refers to the current dom element which the user clicks on the remove button
    //we get the value of the id by getAttribute method
    var id = this.getAttribute('id');
    var todos = get_todos();
    //we use splice to remove a specific element from the javascript array
    todos.splice(id, 1);
    localStorage.setItem('todo', JSON.stringify(todos));

    show();

    return false;
}

function show(){
    var todos = get_todos();
    var html = '<ul align="left" style="text-align=left;">';
    for(var i = 0; i < todos.length; i++){
        html += '<li>' + todos[i]  +'<button class="remove btn waves-effect waves-light btn-small #388e3c green darken-2" id=" ' + i + '">Done</button> </li>';
    }

    html += '</ul>';
    document.getElementById('todos').innerHTML = html;

    var buttons = document.getElementsByClassName('remove');
    for(var i = 0; i < buttons.length; i++){
        buttons[i].addEventListener('click', remove);
    }

    var text = document.getElementById("task").value;
    text = "";
}


document.getElementById('add').addEventListener('click', add);
show();